from tests import *
from ipn import TestPaymentIPN, TestPreapprovalIPN, TestIPNVerification
from preapproval_return_url import TestPreapprovalReturnURL
from payment_return_url import TestPaymentReturnURL